# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotorrent < Formula
  desc "TUI for searching torrents"
  homepage "https://github.com/ismaelpadilla/gotorrent"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ismaelpadilla/gotorrent/releases/download/v0.1.0/gotorrent_0.1.0_macOS_x86_64.tar.gz"
      sha256 "c783e6c4b8a5d0ddb083c32ad62ed8c1ae32093004d34524c9e36c12918d646b"

      def install
        bin.install "gotorrent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ismaelpadilla/gotorrent/releases/download/v0.1.0/gotorrent_0.1.0_macOS_arm64.tar.gz"
      sha256 "fdd4c3a2149451e949805a22fe2a41ca8ced69f290b6b39796db5cda78dce436"

      def install
        bin.install "gotorrent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ismaelpadilla/gotorrent/releases/download/v0.1.0/gotorrent_0.1.0_Linux_x86_64.tar.gz"
      sha256 "bb44aa4cc2955cdd34e26022f33c4bdc9b0c28b5cc01fb6e4cd252f4326758f0"

      def install
        bin.install "gotorrent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ismaelpadilla/gotorrent/releases/download/v0.1.0/gotorrent_0.1.0_Linux_arm64.tar.gz"
      sha256 "b13bf6624578b55b74ac0263aad974a4b699fa933406078e05c44c0d0b5e26d3"

      def install
        bin.install "gotorrent"
      end
    end
  end
end
