# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotorrent < Formula
  desc "TUI for searching torrents"
  homepage "https://github.com/ismaelpadilla/gotorrent"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ismaelpadilla/gotorrent/releases/download/v0.1.0/gotorrent_0.1.0_macOS_x86_64.tar.gz"
      sha256 "de8a7f39013f99b5bd4859a1e8047e3960eb54cd05ed5abc8f81318f010b1440"

      def install
        bin.install "gotorrent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ismaelpadilla/gotorrent/releases/download/v0.1.0/gotorrent_0.1.0_macOS_arm64.tar.gz"
      sha256 "f03e32c9c0d7706523bdf030fdb8355b14938bff336acc72eea171f67a29082b"

      def install
        bin.install "gotorrent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ismaelpadilla/gotorrent/releases/download/v0.1.0/gotorrent_0.1.0_Linux_x86_64.tar.gz"
      sha256 "6672d105d4c0934afb6fc2a99cd90c9e0a008b4ee3bca6a1ce4deae4f6ad81f3"

      def install
        bin.install "gotorrent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ismaelpadilla/gotorrent/releases/download/v0.1.0/gotorrent_0.1.0_Linux_arm64.tar.gz"
      sha256 "f046c1eae007e54375f7935480f2e312585dfd8be3e66a012fd03f1f36e1f768"

      def install
        bin.install "gotorrent"
      end
    end
  end
end
